apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-notes-config
data:
  POSTGRES_DB: demo_notes
  POSTGRES_USER: demo_user
  NODE_ENV: production
  DATABASE_URL: postgresql://demo_user:${POSTGRES_PASSWORD}@postgres:5432/demo_notes
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-notes-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: ${BASE64_POSTGRES_PASSWORD}  # To be replaced during deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: demo-notes-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: demo-notes-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-notes-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
