name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FRONTEND_IMAGE_NAME: ghcr.io/${{ github.repository }}/demo-notes-frontend
  BACKEND_IMAGE_NAME: ghcr.io/${{ github.repository }}/demo-notes-backend
  KUBERNETES_HOST: ${{ secrets.KUBERNETES_PUBLIC_IP }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: |
        npm install -g typescript
        npm run install:all

    - name: Setup frontend
      working-directory: ./frontend
      run: |
        npm install
        npm install --save-dev @vue/compiler-sfc

    - name: Build frontend
      working-directory: ./frontend
      run: |
        npm run build

    - name: Build backend
      working-directory: ./backend
      run: |
        npm run build

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }},${{ env.FRONTEND_IMAGE_NAME }}:latest

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }},${{ env.BACKEND_IMAGE_NAME }}:latest

    - name: Set up kubectl
      uses: kubernetes-sigs/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Test cluster connection
      run: |
        # Verify cluster connection
        kubectl cluster-info
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        # Create image pull secret for GitHub Container Registry
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GITHUB_TOKEN }} \
          --docker-email=${{ github.actor }}@users.noreply.github.com \
          -n default --dry-run=client -o yaml | kubectl apply -f -

        # Update image tags in deployment files
        sed -i "s|{{FRONTEND_IMAGE}}|${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}|g" k8s/frontend.yaml
        sed -i "s|{{BACKEND_IMAGE}}|${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}|g" k8s/backend.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f k8s/
